{"name": "TC kimlik alanına geçersiz karakter girilmesi", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following failure was found in \"test_tc_kimlik_gecersiz_karakter_girme\" (test_kisisel_bilgilerim.TestTobetoKisisel):\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"C:\\Users\\mehme\\Desktop\\test_tobeto\\tests\\test_kisisel_bilgilerim.py\", line 108, in test_tc_kimlik_gecersiz_karakter_girme\n    self.soft_assert(self.assertEqual, profil_olustur.kimlikno_alani,EXPECTED_TEXT, \"\")\n  File \"C:\\Users\\mehme\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"C:\\Users\\mehme\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 885, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"C:\\Users\\mehme\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 878, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: <bound method kisisel_bilgiler.kimlikno_a[76 chars]A40>> != '' : \n\n-+ [1/1] +-", "trace": "self = <test_kisisel_bilgilerim.TestTobetoKisisel testMethod=test_tc_kimlik_gecersiz_karakter_girme>\n\n    @allure.title(\"TC kimlik alanına geçersiz karakter girilmesi\")\n    def test_tc_kimlik_gecersiz_karakter_girme(self):\n    \n        page_base=PageBase(self.driver)\n        giris_yap = Giris(self.driver)\n        profil_olustur = kisisel_bilgiler(self.driver)\n    \n        giris_yap.ana_giris()\n        time.sleep(5)\n        profil_olustur.kullanici_adi_butonuna_tikla()\n        profil_olustur.kullanici_adi_menusundeki_profil_bilgilerine_tikla()\n        profil_olustur.gecersiz_tc_kimlik_no_gir()\n        self.soft_assert(self.assertEqual, profil_olustur.kimlikno_alani,EXPECTED_TEXT, \"\")\n>       self.assert_all()\n\ntests\\test_kisisel_bilgilerim.py:109: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following failure was found in \"test_tc_kimlik_gecersiz_karakter_girme\" (test_kisisel_bilgilerim.TestTobetoKisisel):\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"C:\\Users\\mehme\\Desktop\\test_tobeto\\tests\\test_kisisel_bilgilerim.py\", line 108, in test_tc_kimlik_gecersiz_karakter_girme\nE       self.soft_assert(self.assertEqual, profil_olustur.kimlikno_alani,EXPECTED_TEXT, \"\")\nE     File \"C:\\Users\\mehme\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"C:\\Users\\mehme\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 885, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"C:\\Users\\mehme\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 878, in _baseAssertEqual\nE       raise self.failureException(msg)\nE   AssertionError: <bound method kisisel_bilgiler.kimlikno_a[76 chars]A40>> != '' : \nE   \nE   -+ [1/1] +-"}, "start": 1714736534121, "stop": 1714736543517, "uuid": "fac89397-b889-4a83-b81b-60950b6030a0", "historyId": "df71437b64ab3ff856c4bc65008fc3f7", "testCaseId": "df71437b64ab3ff856c4bc65008fc3f7", "fullName": "tests.test_kisisel_bilgilerim.TestTobetoKisisel#test_tc_kimlik_gecersiz_karakter_girme", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_kisisel_bilgilerim"}, {"name": "subSuite", "value": "TestTobetoKisisel"}, {"name": "host", "value": "ceso"}, {"name": "thread", "value": "25528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_kisisel_bilgilerim"}]}